build:
  image: vyos/vyos-build:equuleus
  script:
      - git clone -b equuleus --single-branch https://github.com/vyos/vyos-build
      - cd vyos-build
      - ./configure --architecture amd64 --build-by "your@email.here" --build-type release --version 1.3.2
      - sudo make iso
  artifacts:
    paths:
      - vyos-build/build/*-amd64.iso

